use portus_core::config::AuthMethod;
use portus_core::session::Protocol;
use portus_lib::commands::{delete_host, resolve_host_secret, save_host, AuthInput};
use uuid::Uuid;

/// Exercises save/resolve/delete against the real OS keychain and the real
/// config.json in this machine's Portus config dir (same directory the
/// running app would use). Passes an explicit id generated by the test
/// itself, and looks the host up by that id rather than by name, so a
/// stale row left behind by an earlier failed run can't be mistaken for
/// the one this run just created. Cleans up after itself either way.
#[test]
fn save_resolve_and_delete_a_password_host_round_trips_through_the_keychain() {
    let id = Uuid::new_v4();
    let config = save_host(
        Some(id),
        "test host (password)".to_string(),
        None,
        Protocol::Ssh,
        "127.0.0.1".to_string(),
        Some(2222),
        Some("testuser".to_string()),
        None,
        AuthInput::Password { password: "s3cret-test-password".to_string() },
        None,
        None,
    )
    .expect("save_host failed");

    let saved = config.hosts.iter().find(|h| h.id == id).expect("saved host missing from config").clone();

    assert!(matches!(saved.auth, AuthMethod::Password { .. }), "expected Password auth, got {:?}", saved.auth);

    let secret = resolve_host_secret(id).expect("resolve_host_secret failed");
    assert_eq!(secret.as_deref(), Some("s3cret-test-password"));

    let config = delete_host(id).expect("delete_host failed");
    assert!(config.hosts.iter().all(|h| h.id != id), "host still present after delete");

    // The keychain entry should be gone too, not just the config row.
    let resolve_after_delete = resolve_host_secret(id);
    assert!(resolve_after_delete.is_err(), "expected resolve to fail for a deleted host");
}

#[test]
fn saving_a_private_key_host_with_no_passphrase_stores_no_keychain_handle() {
    let id = Uuid::new_v4();
    let config = save_host(
        Some(id),
        "test host (key)".to_string(),
        None,
        Protocol::Ssh,
        "127.0.0.1".to_string(),
        Some(2222),
        Some("testuser".to_string()),
        None,
        AuthInput::PrivateKey { path: "/tmp/does-not-need-to-exist".to_string(), passphrase: None },
        None,
        None,
    )
    .expect("save_host failed");

    let saved = config.hosts.iter().find(|h| h.id == id).expect("saved host missing").clone();
    match &saved.auth {
        AuthMethod::PrivateKey { passphrase_handle, .. } => assert!(passphrase_handle.is_none()),
        other => panic!("expected PrivateKey auth, got {other:?}"),
    }

    let secret = resolve_host_secret(id).expect("resolve_host_secret failed");
    assert_eq!(secret, None);

    delete_host(id).expect("delete_host failed");
}
