[package]
name = "portus-ssh"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
portus-core = { workspace = true }
tokio = { workspace = true }
async-trait = { workspace = true }
bytes = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
russh = "0.45"
russh-keys = "0.45"
